// Originally generated by Claude Code on 2026-06-25
package com.example.spring.patch.enumbug;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class EnumBugApplication {
    public static void main(String[] args) {
        SpringApplication.run(EnumBugApplication.class, args);
    }
}
