// Originally generated by Claude Code on 2026-06-25
package com.example.spring.patch.enumbug;

import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;

@AutoConfigureMockMvc
class WidgetPatchTest extends AbstractWidgetPatchTest {
}
