// Originally generated by Claude Code on 2026-06-25
package com.example.spring.patch.enumbug;

import jakarta.json.Json;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.test.web.servlet.MockMvc;

import java.nio.charset.StandardCharsets;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Shared test logic for all Spring Boot versions.
 * Subclass this in each version module with an empty class body.
 *
 * Demonstrates that the JSON Patch `test` operation fails for enum fields in
 * mainline Spring Data REST.
 *
 * Root cause: JsonPatchPatchConverter.valueFromJsonNode returns a raw String for
 * textual JSON nodes instead of wrapping them in a JsonLateObjectEvaluator.
 * TestOperation.perform then calls ObjectUtils.nullSafeEquals(String, Enum),
 * which is always false.
 *
 * Tests 3 and 4 (testStatusReplaceName, testStatusReplaceAmount) demonstrate
 * the bug — they are written to expect success and will fail (red) until the
 * framework is fixed. All other tests pass.
 */
@SpringBootTest
public abstract class AbstractWidgetPatchTest {

    private static final Logger log = LoggerFactory.getLogger(AbstractWidgetPatchTest.class);

    @Autowired
    MockMvc mvc;

    @Autowired
    WidgetRepository widgetRepo;

    Widget saved;

    @BeforeEach
    void setUp() {
        saved = widgetRepo.save(
            Widget.builder()
                .name("Widget One")
                .amount(42)
                .status(JobStatus.NEW)
                .build()
        );
        log.info("Before: id={} name={} amount={} status={}", saved.getId(), saved.getName(), saved.getAmount(), saved.getStatus());
    }

    @AfterEach
    void tearDown() {
        widgetRepo.deleteAll();
    }

    // ── Forward round-robin: test A, replace B ───────────────────────────────

    @Test
    void testNameReplaceAmount() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/name", "Widget One")
                .replace("/amount", 99)
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  id={} name={} amount={} status={}", after.getId(), after.getName(), after.getAmount(), after.getStatus());
        assertThat(after.getAmount()).isEqualTo(99);
    }

    @Test
    void testAmountReplaceStatus() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/amount", 42)
                .replace("/status", "SUCCESS")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  id={} name={} amount={} status={}", after.getId(), after.getName(), after.getAmount(), after.getStatus());
        assertThat(after.getStatus()).isEqualTo(JobStatus.SUCCESS);
    }

    @Test
    // BUG: expects 2xx, gets 400 — PatchException: Test against path '/status' failed
    void testStatusReplaceName() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/status", "NEW")
                .replace("/name", "Updated Widget")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  id={} name={} amount={} status={}", after.getId(), after.getName(), after.getAmount(), after.getStatus());
        assertThat(after.getName()).isEqualTo("Updated Widget");
    }

    // ── Reverse round-robin: test B, replace A ───────────────────────────────

    @Test
    // BUG: expects 2xx, gets 400 — PatchException: Test against path '/status' failed
    void testStatusReplaceAmount() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/status", "NEW")
                .replace("/amount", 99)
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  id={} name={} amount={} status={}", after.getId(), after.getName(), after.getAmount(), after.getStatus());
        assertThat(after.getAmount()).isEqualTo(99);
    }

    @Test
    void testAmountReplaceName() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/amount", 42)
                .replace("/name", "Updated Widget")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  id={} name={} amount={} status={}", after.getId(), after.getName(), after.getAmount(), after.getStatus());
        assertThat(after.getName()).isEqualTo("Updated Widget");
    }

    @Test
    void testNameReplaceStatus() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/name", "Widget One")
                .replace("/status", "SUCCESS")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  id={} name={} amount={} status={}", after.getId(), after.getName(), after.getAmount(), after.getStatus());
        assertThat(after.getStatus()).isEqualTo(JobStatus.SUCCESS);
    }

    // ─────────────────────────────────────────────────────────────────────────

    private void doPatch(String patchJson) throws Exception {
        String uri = "/widgets/" + saved.getId();
        byte[] body = patchJson.getBytes(StandardCharsets.UTF_8);
        mvc.perform(ctx -> {
            MockHttpServletRequest req = new MockHttpServletRequest("PATCH", uri);
            req.setContentType("application/json-patch+json");
            req.setContent(body);
            return req;
        }).andExpect(status().is2xxSuccessful());
    }
}
