// Originally generated by Claude Code on 2026-06-25
package com.example.spring.patch.enumbug;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Data
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Widget {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private Integer amount;

    @Enumerated(EnumType.STRING)
    @Column(columnDefinition = "varchar(255)")
    private JobStatus status;

    @Override
    public String toString() {
        return "Widget{id=" + id + ", name='" + name + "', amount=" + amount + ", status=" + status + '}';
    }
}
