// Originally generated by Claude Code on 2026-06-25
package com.example.spring.patch.enumbug;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

@RepositoryRestResource
public interface WidgetRepository extends JpaRepository<Widget, Long> {
}
