// Originally generated by Claude Code on 2026-06-25
package com.example.spring.patch.enumbug;

import jakarta.persistence.*;

@Entity
public class Widget {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private Integer amount;

    @Enumerated(EnumType.STRING)
    @Column(columnDefinition = "varchar(255)")
    private JobStatus status;

    public Widget() {}

    private Widget(Builder b) {
        this.name = b.name;
        this.amount = b.amount;
        this.status = b.status;
    }

    public static Builder builder() { return new Builder(); }

    public Long getId() { return id; }
    public String getName() { return name; }
    public Integer getAmount() { return amount; }
    public JobStatus getStatus() { return status; }
    public void setName(String name) { this.name = name; }
    public void setAmount(Integer amount) { this.amount = amount; }
    public void setStatus(JobStatus status) { this.status = status; }

    public static class Builder {
        private String name;
        private Integer amount;
        private JobStatus status;

        public Builder name(String name) { this.name = name; return this; }
        public Builder amount(Integer amount) { this.amount = amount; return this; }
        public Builder status(JobStatus status) { this.status = status; return this; }
        public Widget build() { return new Widget(this); }
    }

    @Override
    public String toString() {
        return "Widget{id=" + id + ", name='" + name + "', amount=" + amount + ", status=" + status + '}';
    }
}
