// Originally generated by Claude Code on 2026-06-25
package com.example.spring.patch.enumbug;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.json.Json;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import java.nio.charset.StandardCharsets;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Demonstrates that the JSON Patch `test` operation fails for enum fields in
 * mainline Spring Data REST.
 *
 * Root cause: JsonPatchPatchConverter.valueFromJsonNode returns a raw String for
 * textual JSON nodes instead of wrapping them in a JsonLateObjectEvaluator.
 * TestOperation.perform then calls ObjectUtils.nullSafeEquals(String, Enum),
 * which is always false.
 *
 * Tests 3 and 4 (testStatusReplaceName, testStatusReplaceValue) demonstrate
 * the bug — they are written to expect success and will fail (red) until the
 * framework is fixed. All other tests pass.
 */
@SpringBootTest
@AutoConfigureMockMvc
class WidgetPatchTest {

    private static final Logger log = LoggerFactory.getLogger(WidgetPatchTest.class);

    @Autowired
    MockMvc mvc;

    @Autowired
    WidgetRepository widgetRepo;

    @Autowired
    ObjectMapper objectMapper;

    Widget saved;

    @BeforeEach
    void setUp() throws Exception {
        saved = widgetRepo.save(
            Widget.builder()
                .name("Widget One")
                .amount(42)
                .status(JobStatus.NEW)
                .build()
        );
        log.info("Before: {}", objectMapper.writeValueAsString(saved));
    }

    @AfterEach
    void tearDown() {
        widgetRepo.deleteAll();
    }

    // ── Forward round-robin: test A, replace B ───────────────────────────────

    @Test
    void testNameReplaceAmount() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/name", "Widget One")
                .replace("/amount", 99)
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  {}", objectMapper.writeValueAsString(after));
        assertThat(after.getAmount()).isEqualTo(99);
    }

    @Test
    void testAmountReplaceStatus() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/amount", 42)
                .replace("/status", "SUCCESS")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  {}", objectMapper.writeValueAsString(after));
        assertThat(after.getStatus()).isEqualTo(JobStatus.SUCCESS);
    }

    @Test
    // BUG: expects 200 OK, gets 400 — PatchException: Test against path '/status' failed
    void testStatusReplaceName() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/status", "NEW")
                .replace("/name", "Updated Widget")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  {}", objectMapper.writeValueAsString(after));
        assertThat(after.getName()).isEqualTo("Updated Widget");
    }

    // ── Reverse round-robin: test B, replace A ───────────────────────────────

    @Test
    // BUG: expects 200 OK, gets 400 — PatchException: Test against path '/status' failed
    void testStatusReplaceAmount() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/status", "NEW")
                .replace("/amount", 99)
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  {}", objectMapper.writeValueAsString(after));
        assertThat(after.getAmount()).isEqualTo(99);
    }

    @Test
    void testAmountReplaceName() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/amount", 42)
                .replace("/name", "Updated Widget")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  {}", objectMapper.writeValueAsString(after));
        assertThat(after.getName()).isEqualTo("Updated Widget");
    }

    @Test
    void testNameReplaceStatus() throws Exception {
        var patchJson = Json.createPatchBuilder()
                .test("/name", "Widget One")
                .replace("/status", "SUCCESS")
                .build().toJsonArray().toString();
        log.info("Patch: {}", patchJson);
        doPatch(patchJson);
        var after = widgetRepo.findById(saved.getId()).orElseThrow();
        log.info("After:  {}", objectMapper.writeValueAsString(after));
        assertThat(after.getStatus()).isEqualTo(JobStatus.SUCCESS);
    }

    // ─────────────────────────────────────────────────────────────────────────

    private void doPatch(String patchJson) throws Exception {
        mvc.perform(
            patch("/widgets/" + saved.getId())
                .contentType("application/json-patch+json")
                .characterEncoding(StandardCharsets.UTF_8)
                .content(patchJson)
        ).andExpect(status().is2xxSuccessful());
    }
}
